### ISSUE TITLE
Fix "agent" logger

### ISSUE THREAD

**Issue by frankemax** [mconf/bbb-mobile-sdk#182]
```
/var/log/nginx/html5-client.log.1:{ "nginx": { "access": { "remote_ip": "000.000.000.00", "time": "05/Jun/2023:23:56:20.922 -0300", "host": "xxxxxx", "agent": "okhttp/4.9.2" }, "request_body": {...} }
```
"agent": "okhttp/4.9.2"

talk with @fcecagno about it

**Comment by fcecagno** [comment]
It's not a logger issue.
The problem is that the user agent passed as a header for the http request is okhttp..., which makes it difficult for us to know more about the device and app version calling.

**Comment by frankemax** [comment]
It is the correct user agent. Native apps use this:
### iOS:

```
Ex. bbbMobileSdk/68 CFNetwork/1492.0.1 Darwin/23.3.0
<appname>/<appbuildversion> CFNetwork/<version> Darwin/<version>
```

### Android:

```
Ex: okhttp/4.9.2
okhttp/<version>
```
