### ISSUE TITLE
PiP: iOS implementation

### ISSUE THREAD

**Issue by frankemax** [mconf/bbb-mobile-sdk#759]

**Comment by frankemax** [comment]
https://github.com/jitsi/jitsi-meet/issues/11843
https://github.com/jitsi/jitsi-meet/issues/9437#issuecomment-867370200

**Comment by slmMuc2fly** [comment]
Slam

**Comment by slmMuc2fly** [comment]
Hi

**Comment by frankemax** [comment]
Hi, are you still planning to implement this feature? @matheus-lagreca @christopherpottesc 

It will be GREAT!!!
