### ISSUE TITLE
Android audio devices: review BT behaviour

### ISSUE THREAD

**Issue by frankemax** [mconf/bbb-mobile-sdk#784]
### Teste geral de BT
Comportamento esperado:
- Troca de dispositivo manual desabilita o roteamento automático - o roteamento automático para dispositivo BT só acontece se voce não trocou o dispositivo manualmente (roteamento automático === trocar automático pro audio BT quando parear)
- Caso o BT esteja selecionado, e voce desconectou ele, automaticamente vai trocar pro SPEAKER

#### Os testes abaixo são todos com a permissão ATIVADA
- entrar com dispositivo pareado antes de abrir o app
	- audio sai no BT (ver obs) ⚠️ 
	- BT aparece como selecionado no seletor de audio ✅ 
	- Troca de dispositivos de audio funciona perfeitamente ✅ 
	*obs: incomumente o audio sai no earpiece, e o BT esta erroneamente selecionado, mas o click no botao de refresh resolve isso*
- entrar sem o dispositivo pareado, parear o dispositivo no meio da meeting
	- audio inicialmente sai no speaker, com o speaker selecionado, troca de dispositivo funciona perfeitamente ✅ 
	- quando pareia o BT no meio da meeting o audio troca para o BT ✅ 
	- seletor aparece como BT selecionado ✅ 
	- troca de dispositivo de audio funciona perfeitamente ✅ 
- desconectar o dispositivo BT durante a meeting
	- troca o audio para o speaker ✅ 
	- some BT dos dispostivos disponiveis ✅ 
	- troca de dispositivos de audio funciona perfeitamente ✅ 
- desabilitar o BT do SO durante a meeting
	- troca o audio para o speaker ✅ 
	- some BT dos dispostivos disponiveis ✅ 
	- troca de dispositivos de audio funciona perfeitamente ✅ 
- entrar com o dispositivo pareado antes de abrir o app, desconectar o dispositivo BT (momento 1), conectar o dispositivo BT novamente (momento 2)
	- momento 1: troca e seleciona o speaker, some BT da lista de dispositivos ✅ 
	- momento 2: troca e seleciona o BT ✅ 

#### Os testes abaixo são todos com a permissão DESATIVADA (desative a permissão nas configurações do app e negue a permissão ao abrir o app)
- entrar com dispositivo pareado antes de abrir o app
	- no seletor aparece que voce nao tem a permissao ✅ 
	- quando voce permite e volta para o app, a mensagem some mas ainda nao aparece o dispositivo BT ✅ 
	- ao clicar no botão de refresh o dispositivo BT aparece e é trocado automaticamente para ele ✅ 

#### Os testes abaixo sao todos com a permissão ATIVADA
- entrar com dispositivo pareado antes de abrir o app e trocar entre 3g/wifi
	- inicialmente está saindo pelo BT ✅ 
	- ao trocar entre wifi/3g, tomo reconnect, o com continua saindo pelo BT ✅ 
	- (nao especifico ao BT, mas o reconnect as vezes ocorre somente no audio, tem q dar uma revisada) ⚠️

#### Os testes abaixo são todos com a permissão ATIVADA
*tudo errado aqui, não sei se foi com essas mudanças ou se já estava assim... nem testem esses casos no momento*
- entrar com dispositivo pareado antes de abrir o app, com som saindo no BT, entrar numa breakout e sair
	- TODO ❌ 
- entrar sem o dispositivo pareado, parear o dispositivo dentro da breakout apenas e sair da breakout
	- TODO ❌ 
- entrar com dispositivo pareado antes de abrir o app, desparear o dispositivo dentro da breakout e sair da breakout
	- TODO ❌

**Comment by lfzawacki** [comment]
Pra mim funcionou 100%. Única coisa um pouco estranha foi no reconnect, que o BT sumiu da lista de dispositivos e quando conectou ele voltou. Ouvi áudio no alto falante por 1 segundo e daí foi corretamente pro fone.

**Comment by germanocaumo** [comment]
💯% aqui no Poco X3 Pro

**Comment by frankemax** [comment]
Still not ideal...
https://github.com/mconf/bbb-mobile-sdk/issues/369
